services:
  db:
    image: postgres:17-alpine
    container_name: mylifediary-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mylifediary:local
    container_name: mylifediary-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_FLYWAY_USER: ${DB_USER}
      SPRING_FLYWAY_PASSWORD: ${DB_PASSWORD}
      LOGGING_LEVEL_ROOT: ERROR
      LOGGING_LEVEL_COM_DIEGORAMOS_MYLIFEDIARY: DEBUG
    ports:
      - "8080:8080"

volumes:
  pgdata: