spring.config.import=optional:file:.env[.properties]
spring.application.name=mylifediary
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600}
jwt.refresh-token.expiration-days=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:7}

