spring.config.import=optional:file:.env[.properties]
spring.application.name=mylifediary
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600}
jwt.refresh-token.expiration-days=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:7}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000