spring.config.import=optional:file:.env[.properties]
spring.application.name=mylifediary
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600}
jwt.refresh-token.expiration-days=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:7}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
resend.api-key=${RESEND_API_KEY}
resend.from-email=${RESEND_FROM_EMAIL}
app.base-url=${APP_BASE_URL}